[net]
tickrate = 30

[netres]
limit = 25.0

[infolinks]
discord = "https://discord.gg/tZgNv2wJuJ"
github = "https://github.com/SpaceStories/space-station-14"
wiki = "https://spacestories.club"
patreon = "https://boosty.to/spacestories14"
appeal = "https://discord.gg/tZgNv2wJuJ"

[viewport]
maximum_width = 26

[game]
lobbyduration = 360

[server]
rules_header = "ui-rules-header-corvax"

[discord]
rich_main_icon_id = "corvax"
