- type: gameMapPool
  id: StoriesDefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxAvrite
  - StoriesDelta
  #- StoriesAspid
  - StoriesFland
  #- StoriesOrigin
  - Aspid
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Core
  - Fland
  - Kettle
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  - Packed
